### ISSUE TITLE
Compiling on Sierra?

### ISSUE THREAD

**Issue by rutgerrrrr** [tetsuo/xtray#1]
Can someone update this to compile on Sierra?

**Comment by tetsuo** [comment]
Hello @adaringdesign,

I'm not actively working on this.

But this should be considered experimental anyway. There are many ways of creating tray bar applications (if that's what you need).

From top of my head, for example, take a look at [monu](https://github.com/maxogden/monu). This should compile fine on other platforms as well.

**Comment by rutgerrrrr** [comment]
Hi @tetsuo ,

I see, that's too bad then. I was looking for a way to have a menubar app which would allow me to display some text instead of an icon. The example you mentioned uses [Electron](https://github.com/atom/electron) which unfortunately can't do that (it's what I mainly use). I haven't found anything that would allow me to do that with Electron so I was hoping to be able to play around with your code and modify it but I'm not knowledgeable enough to set it up for Sierra, which I'm currently on.

**Comment by AngryKiller** [comment]
Hi, I'm having the same issue, could you upload the compiled files here please? I really need it, and using Electron is not an option for me as my application would be really big.

**Comment by AngryKiller** [comment]
Even on OS X Yosemite and Xcode 6.3.2, it's not longer compiling...

**Comment by tetsuo** [comment]
Hi @AngryKiller, This uses Swift 1.2 which is no longer supported and I'm also longer maintaining this module. I tried to migrate the Swift code to the latest syntax, but unfortunately it failed, and I don't have much time (or enthusiasm) to learn the new Swift syntax. This was indeed an experimentation and learning project for me, I believe you can easily port the Swift part to Obj-C if you really need this or take a look at the latest Swift syntax.
